theme: jekyll-theme-minimal
title: Scott Weiss | CS 499 ePortfolio
description: This ePortfolio was initially created for my CS 499 capstone class at Southern New Hampshire University (SNHU), and was made to showcase what I've learned throughout the program. Bookmark this to keep an eye on my project updates!
